#include <stdio.h>
#include "myfunctions.h"
int main(){
    int arr[]={1,2,3,4,5};
    printArray(arr, 5);
    findMax(arr, 5);
    findMin(arr, 5);
    sumArray(arr, 5);
    int arr1[]={1,2,3,4,5};
    int arr2[]={6,7,8,9,10};
    sumofArrays(arr1, arr2, 5);
    reverseArray(arr, 5);
    int arr3[]={5,3,4,2,1};
    bubbleSort(arr3, 5);
    getIndexOfElement(arr, 5, 2);
    replaceElement(arr, 5, 3, 10);
    int arr4[]={1,2,3,4,5};
    deleteElement(arr4, 5, 4);
    factorial(5);
    isPrime(11);
    isPrime(9);
    isPalindrome(121);
    isPalindrome(123);
    checkEvenorOdd(14);
    checkEvenorOdd(5);
    isArmstrong(153);
    isArmstrong(149);
    isPerfect(6);
    isPerfect(8);
    eligibletovote(15, 18);
    eligibletovote(22, 18);
    simpleCalculator(5, 4, '+');
    simpleCalculator(7, 3, '-');
    simpleCalculator(3, 5, '*');
    simpleCalculator(25, 8, '/');
    isLeapYear(2016);
    isLeapYear(2018);
    grademarking(96);
    grademarking(83);
    grademarking(79);
    grademarking(62);
    grademarking(58);
    grademarking(43);
    calculateSI(2000, 2, 1);
    isLowerCaseorUpperCase('G');
    isLowerCaseorUpperCase('r');
    isVowel('I');
    isVowel('c');
    convertCase('T');
    convertCase('b');
    sumOfDigits(1234);
    fibonacciSeries(5);
    evenwithinrange(1, 10);
    oddwithinrange(1, 10);
    areaofCircle(2.5);
    areaofRectangle(7, 3);
    areaofTriangle(3, 6);
    areaofSquare(4);
    numberswithinrange(1, 10);
    iterationsum(1, 10);
    sumwithinrange(1, 7);
    isadam(12);
    isadam(14);
}