#include <stdio.h>
#include "myfunctions.h"
int main(){
    int arr[]={1,2,3,4,5};
    printArrayPtr(arr, 5);
    findMaxPtr(arr, 5);
    findMinPtr(arr, 5);
    sumArrayPtr(arr, 5);
    int arr1[]={1,2,3,4,5};
    int arr2[]={6,7,8,9,10};
    sumofArraysPtr(arr1, arr2, 5);
    reverseArrayPtr(arr, 5);
    int arr3[]={5,3,4,2,1};
    bubbleSortPtr(arr3, 5);
    getIndexOfElementPtr(arr, 5, 2);
    replaceElementPtr(arr, 5, 3, 10);
    int arr4[]={1,2,3,4,5};
    deleteElementPtr(arr4, 5, 4);
    factorialPtr(5);
    isPrimePtr(11);
    isPrimePtr(9);
    isPalindromePtr(121);
    isPalindromePtr(123);
    checkEvenorOddPtr(14);
    checkEvenorOddPtr(5);
    isArmstrongPtr(153);
    isArmstrongPtr(149);
    isPerfectPtr(6);
    isPerfectPtr(8);
    eligibletovotePtr(15, 18);
    eligibletovotePtr(22, 18);
    simpleCalculatorPtr(5, 4, '+');
    simpleCalculatorPtr(7, 3, '-');
    simpleCalculatorPtr(3, 5, '*');
    simpleCalculatorPtr(25, 8, '/');
    isLeapYearPtr(2016);
    isLeapYearPtr(2018);
    grademarkingPtr(96);
    grademarkingPtr(83);
    grademarkingPtr(79);
    grademarkingPtr(62);
    grademarkingPtr(58);
    grademarkingPtr(43);
    calculateSIPtr(2000, 2, 1);
    isLowerCaseorUpperCasePtr('G');
    isLowerCaseorUpperCasePtr('r');
    isVowelPtr('I');
    isVowelPtr('c');
    convertCasePtr('T');
    convertCasePtr('b');
    sumOfDigitsPtr(1234);
    fibonacciSeriesPtr(5);
    evenwithinrangePtr(1, 10);
    oddwithinrangePtr(1, 10);
    areaofCirclePtr(2.5);
    areaofRectanglePtr(7, 3);
    areaofTrianglePtr(3, 6);
    areaofSquarePtr(4);
    numberswithinrangePtr(1, 10);
    iterationsumPtr(1, 10);
    sumwithinrangePtr(1, 7);
    isadamPtr(12);
    isadamPtr(14);
}
